# Generated by Django 5.2.4 on 2025-08-05 08:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Confession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anonymous_name', models.CharField(default='Anonymous', max_length=50)),
                ('content', models.TextField()),
                ('category', models.CharField(choices=[('funny', 'Funny'), ('crush', 'Crush'), ('life', 'Life'), ('work', 'Work')], max_length=20)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('reactions_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('reputation', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Reaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('confession', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to='confessions.confession')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='confessions.user')),
            ],
        ),
        migrations.AddField(
            model_name='confession',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='confessions.user'),
        ),
    ]
